apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: master-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /pv/postgres-m-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: for
              operator: In
              values:
                - postgres
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tablet-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /pv/postgres-t-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: for
              operator: In
              values:
                - postgres                