apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: acme-solver
  namespace: istio-ingress
spec:
  hosts:
  - "*"
  gateways:
  - cluster-gateway
  http:
  - name: "acmesolver"
    match:
    - uri:
        prefix: /.well-known/acme-challenge
    route:
    - destination:
        host: cm-acme-http-solver-ffzzg.istio-ingress.svc.cluster.local
        port:
          number: 8089