---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-service
  namespace: istio-ingress
spec:
  hosts:
    - "api.xxx.io"
  gateways:
    - cluster-gateway
  http:
    - match:
        - uri:
            prefix: /v1/users
      route:
        - destination:
            host: user-service.default.svc.cluster.local
            port:
              number: 3000